# Generated by Django 4.2.1 on 2025-11-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('config_schema', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'vas_providers',
            },
        ),
        migrations.CreateModel(
            name='ProviderAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('available_balance', models.FloatField(default='0.0')),
                ('balance_at_provider', models.FloatField(default='0.0')),
                ('vending_sim', models.CharField(blank=True, max_length=50, null=True)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
            options={
                'db_table': 'vas_provider_accounts',
            },
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['provider_code', 'is_active'], name='vas_provide_provide_729c89_idx'),
        ),
        migrations.AddIndex(
            model_name='provideraccount',
            index=models.Index(fields=['provider', 'account_name'], name='vas_provide_provide_038ab1_idx'),
        ),
    ]
