# Generated by Django 4.2.1 on 2025-11-14 15:26

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateField(blank=True, max_length=30, null=True)),
                ('email_verify_token', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'vas_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('api_access_ip', models.CharField(blank=True, max_length=30, null=True)),
                ('account_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], default='Prepaid', max_length=10)),
                ('daily_tranx_limit', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('today_tranx_value', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('today_tranx_date', models.DateField(blank=True, max_length=30, null=True)),
                ('api_secret_key', models.TextField(blank=True, null=True)),
                ('api_token', models.TextField(blank=True, null=True)),
                ('api_token_created', models.DateTimeField(null=True)),
                ('api_token_expire', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('last_updated_balance_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'vas_merchants',
            },
        ),
        migrations.CreateModel(
            name='MerchantFunding',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField()),
                ('funding_ref', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('auto_reversal', 'Auto Reversal'), ('manual_reversal', 'Manual Reversal')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_credited', models.BooleanField(default=False)),
                ('approvedby', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_funding_approvedby', to=settings.AUTH_USER_MODEL)),
                ('createdby', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='merchantfunding_createdby', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_funding', to='merchant.merchant')),
            ],
            options={
                'verbose_name': 'MerchantFunding',
                'verbose_name_plural': 'MerchantFundings',
                'db_table': 'vas_merchant_funding',
            },
        ),
        migrations.CreateModel(
            name='MerchantDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=100)),
                ('discount_value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('createdby', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdby_merchant_discount', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_discounts', to='merchant.merchant')),
            ],
            options={
                'db_table': 'vas_merchant_discount',
            },
        ),
    ]
