# Generated by Django 4.2.1 on 2025-11-14 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('product', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_discounts', to='product.product'),
        ),
        migrations.AddField(
            model_name='merchantdiscount',
            name='updatedby',
            field=models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updatedby_merchant_discount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', related_query_name='merchant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='merchantfunding',
            index=models.Index(fields=['funding_ref', 'is_approved', 'is_active'], name='vas_merchan_funding_64e338_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantdiscount',
            index=models.Index(fields=['discount_type', 'is_active'], name='vas_merchan_discoun_2c75bd_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['merchant_code'], name='merchant_code_index'),
        ),
    ]
