# Generated by Django 4.2.1 on 2025-12-02 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='api_token',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='api_token_created',
            new_name='api_key_updated_at',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='api_token_expire',
            new_name='api_secret_key_updated_at',
        ),
    ]
