# Generated by Django 4.2.1 on 2025-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_rename_api_token_merchant_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='api_access_ip',
        ),
        migrations.AddField(
            model_name='merchant',
            name='api_access_ips',
            field=models.CharField(blank=True, null=True),
        ),
    ]
