# Generated by Django 4.2.1 on 2025-12-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_remove_merchant_api_access_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='api_secret_key',
            new_name='api_secret',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='api_secret_key_updated_at',
            new_name='api_secret_updated_at',
        ),
    ]
