# Generated by Django 4.2.1 on 2025-12-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_rename_api_secret_key_merchant_api_secret_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='today_tranx_value',
            new_name='today_tranx_count',
        ),
    ]
