# Generated by Django 4.2.1 on 2025-11-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_code', models.CharField(max_length=100, unique=True)),
                ('tariff_id', models.CharField(max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'vas_data_packages',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'vas_products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'vas_product_categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('beneficiary_account', models.CharField(max_length=50, unique_for_date='created_at')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Processing', max_length=50)),
                ('is_reverse', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, max_length=230, null=True)),
                ('provider_desc', models.CharField(blank=True, max_length=230, null=True)),
                ('merchant_ref', models.CharField(max_length=230, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='merchant.merchant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='product.product')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category_transactions', to='product.productcategory')),
                ('provider_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='provider.provideraccount')),
            ],
            options={
                'db_table': 'vas_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['category_code', 'is_active'], name='vas_product_categor_e6a532_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='backup_provider_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_provider_account', to='provider.provideraccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_provider_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_provider_account', to='provider.provideraccount'),
        ),
        migrations.AddField(
            model_name='datapackage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_packages', to='product.product'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['beneficiary_account', 'status', 'product', 'provider_ref', 'merchant_ref', 'created_at', 'product_category', 'amount'], name='vas_transac_benefic_fd8906_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code', 'preferred_provider_account', 'backup_provider_account', 'is_active'], name='vas_product_product_273ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='datapackage',
            index=models.Index(fields=['product', 'is_active', 'data_code'], name='vas_data_pa_product_7a9b5e_idx'),
        ),
    ]
