# Generated by Django 4.2.1 on 2025-11-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='backup_provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_provider_account', to='provider.provideraccount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preferred_provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_provider_account', to='provider.provideraccount'),
        ),
    ]
