# Generated by Django 4.2.1 on 2025-12-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_backup_provider_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapackage',
            name='category',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapackage',
            name='creditswitch_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datapackage',
            name='payvantage_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
