# Generated by Django 4.2.1 on 2025-12-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_datapackage_category_datapackage_creditswitch_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapackage',
            name='category',
        ),
        migrations.AddField(
            model_name='datapackage',
            name='network',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datapackage',
            name='plan_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datapackage',
            name='short_desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='creditswitch_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='payvantage_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datapackage',
            name='value',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
