# Generated by Django 4.2.1 on 2025-12-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('product', '0004_remove_datapackage_category_datapackage_network_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPackageProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=100, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('datapackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_packages_provider', to='product.datapackage')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider', to='provider.provider')),
            ],
            options={
                'db_table': 'vas_data_package_providers',
                'indexes': [models.Index(fields=['is_active', 'provider_code'], name='vas_data_pa_is_acti_30a3ea_idx')],
                'unique_together': {('datapackage', 'provider')},
            },
        ),
    ]
