# Generated by Django 4.2.1 on 2025-12-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_datapackageprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapackageprovider',
            name='cost',
        ),
    ]
