# Generated by Django 4.2.1 on 2025-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_datapackageprovider_cost'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datapackageprovider',
            name='vas_data_pa_is_acti_30a3ea_idx',
        ),
        migrations.AddIndex(
            model_name='datapackageprovider',
            index=models.Index(fields=['is_active'], name='vas_data_pa_is_acti_44bc23_idx'),
        ),
    ]
