# Generated by Django 4.2.1 on 2025-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_datapackageprovider_vas_data_pa_is_acti_30a3ea_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapackageprovider',
            name='provider_code',
            field=models.CharField(max_length=100),
        ),
    ]
